spring:
    application:
        name: eureka-server

server:
    port: ${SERVER_PORT:8081}

eureka:
    instance:
        hostname: ${EUREKA_HOSTNAME:localhost}
    client:
        register-with-eureka: false
        fetch-registry: false
        service-url:
            defaultZone: ${EUREKA_URI:http://${eureka.instance.hostname}:${server.port}/eureka/}
